package ru.thevalidator.daivinchikmatcher2.service;

public enum CaseType {

    UNKNOWN,
    PROFILE,
    PROFILE_LIKED_ME,
    PROFILE_URL,
    WARNING,
    LOCATION,
    ADS_DV,
    ADVICE,
    QUESTION,
    SLEEPING,
    TOO_MANY_LIKES,
    CAN_NOT_CONTINUE,
    LONG_TIME_AWAY,
    WANT_TO_MEET,
    SOMEBODY_LIKES_YOU,
    SOMEBODY_LIKES_YOU_AFTER_PROFILE,
    SHOW_QUESTION,
    ONE_BUTTON_ANSWER,
    NO_SUCH_ANSWER,
    QUESTION_AFTER_PROFILE,
    QUESTION_AFTER_INACTIVE,


//    START_MESSAGE,
//+++    TOO_MANY_LIKES,
//+    SOMEBODY_LIKES_YOU,// + AFTER PROFILE
//+++    WANT_TO_MEET,
//    MUTUAL_LIKE,
//+++    LONG_TIME_AWAY,
//+++    ADVERTISEMENT,
//    PROFILE_AFTER_WRONG_ANSWER,
//    GOT_LIKES,
//    SKIP_BUTTON,
//    SKIP_TEXT,
//+++    CAN_NOT_CONTINUE,


    CAPTCHA

}
